-- SQL MIGRATION: CREATE PRODUCT DROPDOWN MAPPING TABLE
-- Execute this in the Supabase SQL Editor

-- 1. Create mapping table
CREATE TABLE IF NOT EXISTS public.product_dropdown_mapping (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint REFERENCES public.dropdown_options(id) ON DELETE CASCADE,
  option_id bigint REFERENCES public.dropdown_options(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE(product_id, option_id)
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.product_dropdown_mapping ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies
CREATE POLICY "Allow public read access" 
ON public.product_dropdown_mapping 
FOR SELECT 
USING (true);

CREATE POLICY "Allow authenticated full access" 
ON public.product_dropdown_mapping 
FOR ALL 
USING (auth.role() = 'authenticated');
